# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- virtualenv -p /usr/bin/python2.7
- sudo apt-get install python-dev
- sudo apt-get install libmysqlclient-dev
- pip install tox
- pip install cython

test_script:
- tox
