# appveyor.yml
---
image:
  - Ubuntu
environment:
  matrix:
  - TOXENV: py25
  - TOXENV: py26
  - TOXENV: py27

build: off

install:
#- pip install tox
- pip install pytest --user
- pip install coverage --user
- pip install caniusepython3 --user
- sh: sudo apt-get install python-dev
#- sh: sudo apt-get install libmysqlclient-dev
- pip install cython

test_script:
- coverage run -m pytest earwigbot
- caniusepython3 -p earwigbot
