# appveyor.yml
---
environment:
  matrix:
  - PYTHON: "C:\\Python27\\python.exe"
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- pip install tox
- pip install cython

test_script:
- tox
